accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LogInView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
]

employMan/urls.py
from django.contrib import admin
from django.urls import path, include
from social_django.urls import urlpatterns as social_django_urlpatterns

app_name = 'accounts'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += social_django_urlpatterns

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('attendance/', views.attendance, name='attendance'),
    path('report/', views.get_attendance_report, name='report'),
    path('combined_report/', views.get_employee_attendance, name="combined_report"),
    path('all_employees/', views.all_employees, name='all_employees'),
    path('add_employee', views.add_employee, name='add_employee'),
    path('add_department/', views.add_department, name='add_department'),
    path('edit_employee/<str:uid>', views.edit_employee, name='edit_employee')
]

base/models.py
from django.db import models
import uuid


class BaseModel(models.Model):
    uid = models.UUIDField(unique=True, primary_key=True, default=uuid.uuid4)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

main/models.py
from django.db import models
from base.models import BaseModel
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.utils import timezone
import uuid


class Department(BaseModel):
    department_name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, null=True, blank=True, default=uuid.uuid4)

    def __str__(self):
        return self.department_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.department_name)
        super(Department, self).save(*args, **kwargs)


class Employee(BaseModel):
    employee = models.CharField(max_length=50, default="Employee")
    slug = models.SlugField(unique=True, null=True, blank=True)
    position = models.CharField(max_length=30, default="Staff")
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='employee')
    phone_number = models.CharField(max_length=20)
    salary_per_day = models.DecimalField(max_digits=8, decimal_places=2)
    hire_date = models.DateField()
    address = models.CharField(max_length=100)

    def __str__(self):
        return str(self.employee)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.employee)
        super(Employee, self).save(*args, **kwargs)


class Attendance(BaseModel):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)
    entry_time = models.TimeField(default="09:00:00")
    leave_time = models.TimeField(default="17:00:00")
    status = models.CharField(max_length=10, choices=(('Present', 'Present'), ('Absent', 'Absent')))

    def __str__(self):
        return f"{self.employee} {self.date}"

main/forms.py
from django import forms
from .models import Employee, Department


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['employee', 'position', 'department', 'phone_number', 'salary_per_day', 'hire_date', 'address']


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['department_name']

main/views.py
from django.shortcuts import render, redirect
from django.db.models import Count, Sum, Q
from main.models import Employee, Attendance
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import EmployeeForm, DepartmentForm


@login_required
def home(request):
    employees = Employee.objects.all()
    total_employees = employees.count()
    context = {'employees': employees, 'total_employees': total_employees}
    return render(request, 'main/index.html', context)


@login_required
def all_employees(request):
    employees = Employee.objects.all()
    context = {'employees': employees}
    return render(request,'main/all_employees.html', context)


@login_required
def add_employee(request):
    form = EmployeeForm()
    if request.user.is_superuser:
        if request.method == 'POST':
            form = EmployeeForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('main:home')
        else:
            form = EmployeeForm()
    return render(request, 'main/add_employee.html', {'form': form})


@login_required
def add_department(request):
    form = DepartmentForm()
    if request.user.is_superuser:
        if request.method == 'POST':
            form = DepartmentForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('main:home')
        else:
            form = DepartmentForm()
    return render(request, 'main/add_department.html', {'form': form})


@login_required
def attendance(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            date = request.POST.get('date')
            if Attendance.objects.filter(date=date).exists():
                messages.error(request, f"Attendance for {date} already exists.")
                return redirect('main:attendance')
            else:
                for employee, status in request.POST.items():

                    if employee.startswith('status-'):
                        employee_id = employee[7:]
                        employee = Employee.objects.get(slug=employee_id)
                        new_attendance = Attendance.objects.create(employee=employee, date=date, status=status)
                        new_attendance.save()

                for employee, status in request.POST.items():
                    if employee.startswith('entry-'):
                        employee_id = employee[6:]
                        employee = Employee.objects.get(slug=employee_id)
                        attendance_obj = Attendance.objects.get(employee=employee, date=date)
                        attendance_obj.entry_time = status
                        attendance_obj.save()

                    elif employee.startswith('leave-'):
                        employee_id = employee[6:]
                        employee = Employee.objects.get(slug=employee_id)
                        attendance_obj = Attendance.objects.get(employee=employee, date=date)
                        attendance_obj.leave_time = status
                        attendance_obj.save()

                messages.success(request, f"Attendance for {date} added.")
                return redirect('main:home')
        else:
            employees = Employee.objects.all()
            context = {'employees': employees}
            return render(request, 'main/attendance_table.html', context)
    else:
        return redirect('main:home')


@login_required
def get_attendance_report(request):
    employees = Employee.objects.all()
    context = {'employees': employees}
    if request.user.is_superuser:
        if request.method == 'POST':
            start = request.POST.get('start')
            end = request.POST.get('end')
            if request.POST.get('username'):
                username = request.POST.get('username')
                if username == 'All Employees':
                    attendance_list = Attendance.objects.filter(date__range=(start, end))
                    context = {'attendance_list': attendance_list, 'employees': employees}
                    return render(request, 'main/attendance_report.html', context)
                else:
                    employee = Employee.objects.get(slug=username)
                    attendance_list = Attendance.objects.filter(employee=employee, date__range=(start, end))
                    context = {'attendance_list': attendance_list, 'employees': employees}
                    return render(request, 'main/attendance_report.html', context)
    return render(request, 'main/attendance_report.html', context)


@login_required
def get_employee_attendance(request):
    employees = Employee.objects.all()
    context = {'employees': employees}
    if request.user.is_superuser:
        if request.method == 'POST':
            start = request.POST.get('start')
            end = request.POST.get('end')
            if request.POST.get('username'):
                username = request.POST.get('username')
                if username == 'All Employees':
                    attendance_list = Attendance.objects.filter(date__range=(start, end)).values('employee__employee', 'employee__department__department_name', 'employee__salary_per_day').annotate(present=Count('status', filter=Q(status='Present')), absent=Count('status', filter=Q(status='Absent')))
                    print(attendance_list)
                    emp_sal = []
                    for salary in attendance_list:
                        sal = salary['present'] * salary['employee__salary_per_day']
                        emp_sal.append(salary['employee__salary_per_day'] * salary['present'])
                        salary['employee__salary'] = sal
                    print(emp_sal)
                    context = {'attendance_list': attendance_list, 'start': start, 'end': end, 'employees': employees, 'emp_sal': emp_sal}
                    return render(request, 'main/attendance_combined.html', context)
                else:
                    employee = Employee.objects.get(slug=username)
                    attendance_list = Attendance.objects.filter(employee=employee, date__range=(start, end)).values('employee__employee').annotate(present=Count('status', filter=Q(status='Present')), absent=Count('status', filter=Q(status='Absent')))
                    total_salary = attendance_list.values('present')
                    for salary in total_salary:
                        print(salary['present'] * employee.salary_per_day)
                    context = {'attendance_list': attendance_list, 'start': start, 'end': end, 'employees': employees}
                    return render(request, 'main/attendance_combined.html', context)
    return render(request, 'main/attendance_combined.html', context)


@login_required
def edit_employee(request, uid):
    employee = Employee.objects.get(uid=uid)
    form = EmployeeForm(instance=employee)
    if request.user.is_superuser:
        if request.method == 'POST':
            form = EmployeeForm(request.POST, instance=employee)
            if form.is_valid():
                form.save()
                messages.success(request, 'Employee has been updated.')
                return redirect('main:all_employees')
        else:
            form = EmployeeForm(instance=employee)
    return render(request,'main/edit_employee.html', {'form': form, 'employee': employee})

templates/main/all_employees.html
{% extends 'main/base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block title %}
    All Employess
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="home-tab">

                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active ps-0" id="home-tab" href="{% url 'main:home' %}" role="tab">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" id="profile-tab" href="{% url 'main:attendance' %}">Attendance</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" id="contact-tab" href="{% url 'main:report' %}">Report</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link border-0" id="more-tab" href="{% url 'main:combined_report' %}" role="tab">Combined Report</a>
                    </li>
                  </ul>
                  <div>
                    <div class="btn-wrapper">
                      <a href="#" class="btn btn-otline-dark align-items-center"><i class="icon-share"></i> Share</a>
                      <a href="#" class="btn btn-otline-dark"><i class="icon-printer"></i> Print</a>
                      <a href="#" class="btn btn-primary text-white me-0"><i class="icon-download"></i> Export</a>
                    </div>
                  </div>
                </div>

                <div class="tab-content tab-content-basic">

                    <div class="row flex-grow">
                          <div class="col-12 grid-margin stretch-card">
                            <div class="card card-rounded">
                              <div class="card-body">
                                <div class="d-sm-flex justify-content-between align-items-start">
                                  <div>
                                    <h4 class="card-title card-title-dash">Employees</h4>
                                   <p class="card-subtitle card-subtitle-dash">All Employees</p>
                                  </div>
                                  <div>
                                    <button class="btn btn-primary btn-lg text-white mb-0 me-0" type="button"><i class="mdi mdi-account-plus"></i>Add new Employee</button>
                                  </div>
                                </div>
                                {% bootstrap_messages %}
                                <div class="table-responsive  mt-1">
                                  <table class="table select-table">
                                    <thead>
                                      <tr>
                                        <th>Name</th>
                                        <th>Department</th>
                                        <th>Info</th>
                                        <th>Status</th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      {% for emp in employees %}
                                      <tr>
                                        <td>
                                          <div class="d-flex ">
                                            <img src="{% static 'assets/images/faces/profile.png' %}" alt="">
                                            <div>
                                              <h6><a href="{% url 'main:edit_employee' emp.uid %} ">{{ emp.employee }}</a></h6>
                                              <p>{{ emp.position }}</p>
                                            </div>
                                          </div>
                                        </td>
                                        <td>
                                          <h6>{{ emp.department }}</h6>
                                          <p></p>
                                        </td>
                                          <td>
                                          <h6>{{ emp.slug }}</h6>
                                          <p>{{ emp.phone_number }}</p>
                                        </td>
                                        <td><div class="badge badge-opacity-success">Active</div></td>
                                      </tr>
                                      {% endfor %}
                                    </tbody>
                                  </table>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/attendance_report.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
    Attendance Report
{% endblock %}


{% block content %}
        <div class="row">
            <div class="col-sm-12">
            <div class="home-tab">
                <div class="d-sm-flex align-items-center justify-content-between border-bottom">
                  <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link ps-0" id="home-tab" href="{% url 'main:home' %}" role="tab">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" id="profile-tab" href="{% url 'main:attendance' %}">Attendance</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link active" id="contact-tab" href="{% url 'main:report' %}">Report</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link border-0" id="more-tab" href="{% url 'main:combined_report' %}" role="tab">Combined Report</a>
                    </li>
                  </ul>
                  <div>
                    <div class="btn-wrapper">
                      <a href="#" class="btn btn-otline-dark align-items-center"><i class="icon-share"></i> Share</a>
                      <a href="#" class="btn btn-otline-dark"><i class="icon-printer"></i> Print</a>
                      <a href="#" class="btn btn-primary text-white me-0"><i class="icon-download"></i> Export</a>
                    </div>
                  </div>
                </div>
                <br>
                <div class="col-lg-12 grid-margin stretch-card">

              <div class="card">
                <div class="card-body">
                  <h3 class="card-title">Attendance Report</h3>
                <form method="POST" action="{% url 'main:report' %}">
                    {% csrf_token %}
                <div class="col-sm-3">
                    <label for="start">Start date</label>
                    <div id="datepicker-popup" class="input-group date datepicker navbar-date-picker">
                      <span class="input-group-addon input-group-prepend border-right">
                        <span class="icon-calendar input-group-text calendar-icon"></span>
                      </span>
                        <input type="date" id="start" name="start" class="form-control" value="{{ date|date:'Y-m-d' }}" required>
                    </div>
                </div>
                <br>

                <div class="col-sm-3">
                    <label for="end">End date</label>
                    <div id="datepicker-popup" class="input-group date datepicker navbar-date-picker">
                      <span class="input-group-addon input-group-prepend border-right">
                        <span class="icon-calendar input-group-text calendar-icon"></span>
                      </span>
                        <input type="date" id="end" name="end" class="form-control" value="{{ date|date:'Y-m-d' }}" required>
                    </div>
                </div>
                    <br>
                <div class="col-sm-3">
                    <label for="username">Employee</label>
                    <select class="form-select" name="username" aria-label="Default select example">
                      <option selected>All Employees</option>
                        {% for employee in employees %}
                            <option value="{{ employee.slug }}">{{ employee.employee }}</option>
                        {% endfor %}
                    </select>
                </div>
                    <br>
                    <div class="col-sm-3">
                        <button type="submit" class="btn btn-primary" style="color:white">Submit</button>
                    </div>
                </form>
                {% if attendance_list %}
                  <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Employee</th>
                          <th>Department</th>
                          <th>Date</th>
                          <th>Status</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for attendance in attendance_list %}
                        <tr>
                          <td>{{ attendance.employee.employee }}</td>
                          <td>{{ attendance.employee.department }}</td>
                          <td>{{ attendance.date }}</td>
                          <td>{{ attendance.status }}</td>
                        </tr>
                      {% endfor %}
                      </tbody>
                    </table>
                  </div>
                {% endif %}
                </div>
              </div>
            </div>
            </div>
            </div>
        </div>
{% endblock %}

{% block scripts %}
    <script>
        let start =document.getElementById("start");
        let end = document.getElementById("end");
        const today = new Date().toISOString().split("T")[0];
        start.value = today;
        end.value = today;
        end.min = today;

        start.addEventListener("input", () => {
            end.min = start.value;
            const start1 = new Date(start.value);
            end.valueAsDate = new Date(start1.getTime() + 86400000);
        });
    </script>
{% endblock %}

templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock %} - Narayan Iron</title>
    {% block head %}
    {% endblock %}
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'assets/vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/typicons/typicons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/simple-line-icons/css/simple-line-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
  <!-- end inject -->
  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'assets/js/select.dataTables.min.css' %}">
  <!-- End plugin css for this page -->
  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'assets/css/vertical-layout-light/style.css' %}">
  <!-- end inject -->
  <link rel="shortcut icon" href="{% static 'assets/images/narayan-logo.png' %}" />
</head>
<body>
<div class="container-scroller">
    <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">

      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
        <div class="me-3">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
            <span class="icon-menu"></span>
          </button>
        </div>
        <div>
          <a class="navbar-brand brand-logo" href="{% url 'main:home' %}">
{#            <img src="{% static 'assets/images/logo.svg' %}" alt="logo" />#}
              <h3><b>Narayan<span style="color: coral">Iron</span></b></h3>
          </a>
          <a class="navbar-brand brand-logo-mini" href="{% url 'main:home' %}">
            <img src="{% static 'assets/images/narayan-logo.png' %}" alt="logo" />
          </a>
        </div>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-top">
        <ul class="navbar-nav">
          <li class="nav-item font-weight-semibold d-none d-lg-block ms-0">
            <h1 class="welcome-text">Hello, <span class="text-black fw-bold">{{ request.user.first_name }}</span></h1>
            <h3 class="welcome-sub-text">Welcome to NarayanIron</h3>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
          <li class="nav-item d-none d-lg-block">
            <div id="datepicker-popup" class="input-group date datepicker navbar-date-picker">
              <span class="input-group-addon input-group-prepend border-right">
                <span class="icon-calendar input-group-text calendar-icon"></span>
              </span>
              <input type="text" class="form-control">
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link count-indicator" id="countDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="icon-bell"></i>
              <span class="count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="countDropdown">
              <a class="dropdown-item py-3">
                <p class="mb-0 font-weight-medium float-left">No Messages </p>
              </a>
              <div class="dropdown-divider"></div>
            </div>
          </li>
          <li class="nav-item dropdown d-none d-lg-block user-dropdown">
            <a class="nav-link" id="UserDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
              <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/profile.png' %}" alt="Profile image"> </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <div class="dropdown-header text-center">
                <img class="img-md rounded-circle" width="40px" src="{% static 'assets/images/faces/profile.png' %}" alt="Profile image">
                <p class="mb-1 mt-3 font-weight-semibold">{{ request.user.first_name }}</p>
                <p class="fw-light text-muted mb-0">{{ request.user.email }}</p>
              </div>
              {% if request.user.is_superuser %}
              <a class="dropdown-item" {% url 'admin:login' %}><i class="dropdown-item-icon mdi mdi-account-outline text-primary me-2"></i>Django Admin</a>
              {% endif %}
              <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-account-outline text-primary me-2"></i> My Profile</a>
              <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-calendar-check-outline text-primary me-2"></i> Activity</a>
              <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="dropdown-item-icon mdi mdi-power text-primary me-2"></i>Sign Out</a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <div class="container-fluid page-body-wrapper">
        <div id="right-sidebar" class="settings-panel">
        <i class="settings-close ti-close"></i>
        <ul class="nav nav-tabs border-top" id="setting-panel" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="todo-tab" data-bs-toggle="tab" href="#todo-section" role="tab" aria-controls="todo-section" aria-expanded="true">TO DO LIST</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="chats-tab" data-bs-toggle="tab" href="#chats-section" role="tab" aria-controls="chats-section">CHATS</a>
          </li>
        </ul>
      </div>
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:home' %}">
              <i class="mdi mdi-grid-large menu-icon"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item nav-category">Attendance</li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:attendance' %}">
              <i class="menu-icon mdi mdi-card-text-outline"></i>
              <span class="menu-title">Take Attendance</span>
              <i class="menu-arrow"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:report' %}">
              <i class="menu-icon mdi mdi-layers-outline"></i>
              <span class="menu-title">Attendance Report</span>
              <i class="menu-arrow"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:combined_report' %}">
              <i class="menu-icon mdi mdi-layers-outline"></i>
              <span class="menu-title">Combined Report</span>
              <i class="menu-arrow"></i>
            </a>
          </li>
          <li class="nav-item nav-category">Employees</li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:all_employees' %}">
              <i class="menu-icon mdi mdi-card-text-outline"></i>
              <span class="menu-title">All Employees</span>
              <i class="menu-arrow"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:add_employee' %}">
              <i class="menu-icon mdi mdi-layers-outline"></i>
              <span class="menu-title">Add Employee</span>
              <i class="menu-arrow"></i>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:add_department' %}">
              <i class="menu-icon mdi mdi-layers-outline"></i>
              <span class="menu-title">Add Department</span>
              <i class="menu-arrow"></i>
            </a>
          </li>
        </ul>
      </nav>
            <div class="main-panel">
                <div class="content-wrapper">
                {% block content %}
                {% endblock %}
            </div>
          <footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Narayan Iron & Steel Industries.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2023. All rights reserved.</span>
          </div>
        </footer>
          </div>
    </div>
</div>

<!-- plugins:js -->
  <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
  {% block scripts %}
  {% endblock %}
  <!-- end inject -->
  <!-- Plugin js for this page -->
  <script src="{% static 'assets/vendors/chart.js/Chart.min.js' %}"></script>
  <script src="{% static 'assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'assets/vendors/progressbar.js/progressbar.min.js' %}"></script>

  <!-- End plugin js for this page -->
  <!-- inject:js -->
  <script src="{% static 'assets/js/off-canvas.js' %}"></script>
  <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
  <script src="{% static 'assets/js/template.js' %}"></script>
  <script src="{% static 'assets/js/settings.js' %}"></script>
  <script src="{% static 'assets/js/todolist.js' %}"></script>
  <!-- end inject -->
  <!-- Custom js for this page-->
  <script src="{% static 'assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
  <script src="{% static 'assets/js/dashboard.js' %}"></script>
  <script src="{% static 'assets/js/Chart.roundedBarCharts.js' %}"></script>
  <!-- End custom js for this page-->
</body>
</html>